// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1UW66HfQYy1zr71spLkGgH7HQtztjTFg',
    appId: '1:237040370145:web:0f4ddda29a75a8685052a0',
    messagingSenderId: '237040370145',
    projectId: 'smartplant-7b16a',
    authDomain: 'smartplant-7b16a.firebaseapp.com',
    databaseURL: 'https://smartplant-7b16a-default-rtdb.firebaseio.com',
    storageBucket: 'smartplant-7b16a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp74Ma-5L_ETyRW77ACc6hkGjyL27Gw08',
    appId: '1:237040370145:android:0034efcc602c14275052a0',
    messagingSenderId: '237040370145',
    projectId: 'smartplant-7b16a',
    databaseURL: 'https://smartplant-7b16a-default-rtdb.firebaseio.com',
    storageBucket: 'smartplant-7b16a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1SdIFX9ur5V1Htx8W_K8OwMYdgDMQ-Pg',
    appId: '1:237040370145:ios:04d3d43ecb12bed45052a0',
    messagingSenderId: '237040370145',
    projectId: 'smartplant-7b16a',
    databaseURL: 'https://smartplant-7b16a-default-rtdb.firebaseio.com',
    storageBucket: 'smartplant-7b16a.firebasestorage.app',
    iosBundleId: 'com.example.flowerapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1SdIFX9ur5V1Htx8W_K8OwMYdgDMQ-Pg',
    appId: '1:237040370145:ios:04d3d43ecb12bed45052a0',
    messagingSenderId: '237040370145',
    projectId: 'smartplant-7b16a',
    databaseURL: 'https://smartplant-7b16a-default-rtdb.firebaseio.com',
    storageBucket: 'smartplant-7b16a.firebasestorage.app',
    iosBundleId: 'com.example.flowerapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1UW66HfQYy1zr71spLkGgH7HQtztjTFg',
    appId: '1:237040370145:web:ffc5e8c2dfc9e6f95052a0',
    messagingSenderId: '237040370145',
    projectId: 'smartplant-7b16a',
    authDomain: 'smartplant-7b16a.firebaseapp.com',
    databaseURL: 'https://smartplant-7b16a-default-rtdb.firebaseio.com',
    storageBucket: 'smartplant-7b16a.firebasestorage.app',
  );
}
